# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1260454605);
user_pref("app.update.lastUpdateTime.background-update-timer", 1260454604);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1260454604);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1260383901);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1260383900);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.3a1pre");
user_pref("browser.startup.page", 0);
user_pref("capability.principal.codebase.p0.granted", "UniversalPreferencesWrite UniversalXPConnect UniversalPreferencesRead");
user_pref("capability.principal.codebase.p0.id", "file://");
user_pref("capability.principal.codebase.p0.subjectName", "");
user_pref("capability.principal.codebase.p1.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p1.id", "file://");
user_pref("capability.principal.codebase.p1.subjectName", "");
user_pref("capability.principal.codebase.p2.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p2.id", "file://");
user_pref("capability.principal.codebase.p2.subjectName", "");
user_pref("dom.allow_scripts_to_close_windows", true);
user_pref("extensions.enabledItems", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.7a1pre");
user_pref("extensions.lastAppVersion", "3.7a1pre");
user_pref("extensions.update.notifyUser", false);
user_pref("idle.lastDailyNotification", 1263547390);
user_pref("intl.charsetmenu.browser.cache", "UTF-8, ISO-8859-1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.last_vacuum", 1263325374);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.fileuri.strict_origin_policy", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1265902902);
